### ISSUE TITLE
isBigInt 判断有误

### ISSUE THREAD

**Issue by lomocc** [nshen/narrowing#1]
想法不错哈。

我来给你提 2 个 Bug 和 建议：

- `isBigInt` 好像判断错了

```js
function isBigInt(value: unknown): value is bigint {
  return typeof value === 'boolean';
}
```
应该是
```js
typeof value === 'bigint'
```

- 建议 `has` 重命名为 `hasOwnProperty` 或者 `hasProperty`，单纯的 `has` 不好理解

**Comment by nshen** [comment]
非常感谢哈，`isBigInt` 好大一个bug 呀 。已经更新。

`hasProperty` 确实好点，不过简单起见 `has` 也还好，还是先不改了。
